### ISSUE TITLE
Błąd "unexpected string...."

### ISSUE THREAD

**Issue by LukaszZ-Sa** [jnalepka/GrentonTutorials#2]
Dzień dobry,

Dziękuje za udostępnienie opisu konfiguracji połączenia node red - google - grenton. Fajna sprawa. 

Próbuje przejść przez opis, jednak otrzymuje błąd:

node: response switch Off
msg : string[40]
"Unexpected string in JSON at position 18"

Co robię źle? w którym miejscu popełniłem w node red błąd (a może w grentonie)? Wydaje mi się, ze przepisałem wszystko zgodnie z Pana opisem. Czy mogę prosić o pomoc?

**Comment by jnalepka** [comment]
a taki sam komunikat pojawia się analogicznie dla response switch On ?

**Comment by jnalepka** [comment]
Proszę sprawdzić, czy w Grentonie w obiekcie Listener ResponseType ustawione jest na JSON

**Comment by LukaszZ-Sa** [comment]
Tak, identyczny

śr., 4 sie 2021, 16:09 użytkownik jnalepka ***@***.***>
napisał:

**Comment by LukaszZ-Sa** [comment]
Witam,

Tak w Grenton jest ustawiony Json. A jak sprawdzić pozycję 18? Gdzie mogę
odczytać co to za pozycja?

śr., 4 sie 2021, 16:12 użytkownik jnalepka ***@***.***>
napisał:

**Comment by jnalepka** [comment]
Najprawdopodobniej w  response switch Off i  response switch On u Ciebie źle sformuowany jest JSON, może brakuje przecinków?

**Comment by jnalepka** [comment]
> Witam, Tak w Grenton jest ustawiony Json. A jak sprawdzić pozycję 18? Gdzie mogę odczytać co to za pozycja?

Można sprawdzić to otwierając edycję obiektu i od początku przesunąć kursor na 18 pozycję, w tym miejscu będzie błąd, czyli według tutoriala nie wstawiłeś przecinka po 

`{
"object":"Lamp"
`

przecinek powinien rozdzielać poszczególne elementy JSON-a, czyli tak jak w tutorialu:

`
{
"object":"Lamp",
"method":"SwitchOn"
}
`

**Comment by LukaszZ-Sa** [comment]
Dziękuję,

Tak to była kwestia przecinka. Bardzo dziękuję za pomoc i poświęcony czas.

śr., 4 sie 2021, 17:44 użytkownik jnalepka ***@***.***>
napisał:
